<a href="https://colab.research.google.com/github/Leonanda1013/DataLoverz/blob/main/Competition/Playground/Playground_HeartDisease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
dfTrain = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e2/train.csv')
dfTrain = dfTrain.set_index('id')

In [4]:
dfTrain.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
id,,,,,,,,,,,,,,
0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [5]:
dfTrain.shape

(630000, 14)

In [6]:
dfTrain.duplicated().sum()

np.int64(0)

In [7]:
dfTrain.isnull().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [8]:
dfTrain.info(
)

<class 'pandas.core.frame.DataFrame'>
Index: 630000 entries, 0 to 629999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Age                      630000 non-null  int64
 1   Sex                      630000 non-null  int64
 2   Chest pain type          630000 non-null  int64
 3   BP                       630000 non-null  int64
 4   Cholesterol              630000 non-null  int64
 5   FBS over 120             630000 non-null  int64
 6   EKG results              630000 non-null  int64
 7   Max HR                   630000 non-null  int64
 8   Exercise angina          630000 non-null  int64
 9   ST depression            630000 non-null  float64
 10  Slope of ST              630000 non-null  int64
 11  Number of vessels fluro  630000 non-null  int64
 12  Thallium                 630000 non-null  int64
 13  Heart Disease            630000 non-null  object
dtypes: float64(1), int64(12), object(1)
memory usage: 72.1+ MB

In [9]:
dfTrain.describe()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,54.136706,0.714735,3.312752,130.497433,245.011814,0.079987,0.981660,152.816763,0.273725,0.716028,1.455871,0.451040,4.618873
std,8.256301,0.451541,0.851615,14.975802,33.681581,0.271274,0.998783,19.112927,0.445870,0.948472,0.545192,0.798549,1.950007
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000
25%,48.000000,0.000000,3.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.000000,3.000000
50%,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,1.000000,0.000000,3.000000
75%,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,166.000000,1.000000,1.400000,2.000000,1.000000,7.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000

In [10]:
dfTrain.columns = dfTrain.columns.str.replace(' ', '_')

In [11]:
dfTrain.info()

<class 'pandas.core.frame.DataFrame'>
Index: 630000 entries, 0 to 629999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Age                      630000 non-null  int64
 1   Sex                      630000 non-null  int64
 2   Chest_pain_type          630000 non-null  int64
 3   BP                       630000 non-null  int64
 4   Cholesterol              630000 non-null  int64
 5   FBS_over_120             630000 non-null  int64
 6   EKG_results              630000 non-null  int64
 7   Max_HR                   630000 non-null  int64
 8   Exercise_angina          630000 non-null  int64
 9   ST_depression            630000 non-null  float64
 10  Slope_of_ST              630000 non-null  int64
 11  Number_of_vessels_fluro  630000 non-null  int64
 12  Thallium                 630000 non-null  int64
 13  Heart_Disease            630000 non-null  object
dtypes: float64(1), int64(12), object(1)
memory usage: 72.1+ MB

In [12]:
for col in dfTrain.columns:
    print(col)
    print(dfTrain[col].unique())
    print()

Age
[58 52 56 44 38 59 60 48 41 42 53 50 65 46 62 57 54 66 51 55 43 71 63 61
 35 49 47 67 64 45 40 70 69 37 76 34 68 39 74 77 29 75]

Sex
[1 0]

Chest_pain_type
[4 1 2 3]

BP
[152 125 160 134 140 138 130 120 150 108 110 178 124  94 112 128 118 100
 105 172 180 145 132 142 122 135 136 126 106 101 115 156 170 146 192 102
 117 148 104 200 165 129 174 123 144 158 133 103 147 155 149 109 168 111
 154 127 114 116 175 141 131 162  99  96  95 184]

Cholesterol
[239 325 188 229 234 283 246 245 212 197 230 263 244 231 274 282 199 226
 204 185 177 250 211 303 201 266 256 219 222 249 235 295 258 271 304 277
 203 228 269 208 254 268 206 299 221 196 240 298 288 265 198 270 243 309
 233 330 255 315 261 294 223 214 273 286 267 260 236 289 252 275 302 224
 305 218 340 248 308 300 149 209 225 213 207 180 192 327 232 200 341 227
 322 220 311 210 172 247 360 306 318 215 335 205 178 182 242 168 564 353
 195 253 407 276 313 354 257 307 409 217 175 290 321 184 174 281 319 186
 417 193 293 164 166 160 216 183 326 237 158 259 262 170 464 150 264 165
 284 138 173 130 126 202]

FBS_over_120
[0 1]

EKG_results
[0 2 1]

Max_HR
[158 171 151 150 125 147 152 173 160 142 161 163 162 169 172 145 166  96
 122 132 168 131 140 143 154 105 159 170 149 139 178 174 165 181 148 156
 155 175 182 120 126 146 138 180 157 164 114  99 144 179 153 141 192 109
 130 116 106 167 108 112 117 194 129 186 133 188 111 103 123 134 177  95
 202 121 113  97 184 185 190 115  88 118 136 195 124 128  71 187 127 137
 110  94 201]

Exercise_angina
[1 0]

ST_depression
[3.6  0.   1.   3.8  1.6  0.8  1.2  0.6  0.2  1.8  2.2  0.3  1.4  1.5
 2.8  3.   0.9  1.1  3.2  1.9  4.   2.   1.3  2.6  0.5  0.4  0.1  2.5
 2.4  4.9  3.9  2.3  3.4  2.1  3.5  4.3  4.2  4.5  3.1  4.6  2.9  2.7
 4.8  5.   4.4  6.   0.7  3.3  5.4  1.7  2.12 3.7  4.1  5.2  6.2  6.1
 5.6  0.64 5.8  4.7  5.1  1.64 5.5  5.9  5.3  0.06]

Slope_of_ST
[2 1 3]

Number_of_vessels_fluro
[2 0 3 1]

Thallium
[7 3 6]

Heart_Disease
['Presence' 'Absence']

In [13]:
dfTrain['Heart_Disease'].value_counts()

Heart_Disease
Absence     347546
Presence    282454
Name: count, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

dfTrain['Heart_Disease'] = le.fit_transform(dfTrain['Heart_Disease'])

In [15]:
dfTrain['Heart_Disease'].value_counts()

Heart_Disease
0    347546
1    282454
Name: count, dtype: int64

In [16]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [40]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.4 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [41]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

In [43]:
models = {
    "linear": LinearRegression(),
    "rf": RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ),
    "xgb": XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    ),
    "lgbm": LGBMRegressor(
        n_estimators=500,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42
    ),
    "cat": CatBoostRegressor(
        iterations=500,
        learning_rate=0.05,
        depth=6,
        verbose=0,
        random_state=42
    )
}

In [44]:
X = dfTrain.drop('Heart_Disease', axis=1)
y = dfTrain['Heart_Disease']

In [45]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [46]:
from sklearn.metrics import mean_absolute_error

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_valid)
    mae = mean_absolute_error(y_valid, preds)

    results[name] = mae

results

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.118373 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 417
[LightGBM] [Info] Number of data points in the train set: 504000, number of used features: 13
[LightGBM] [Info] Start training from score 0.448448

{'linear': 0.24234797070835326,
 'rf': 0.17596928571428574,
 'xgb': 0.17207229137420654,
 'lgbm': 0.17209256441501614,
 'cat': 0.17129265377516142}

In [47]:
from sklearn.model_selection import KFold, cross_val_score
import pandas as pd
import numpy as np

kf = KFold(n_splits=5, shuffle=True, random_state=42)

cv_results = {}

for name, model in models.items():
    scores = -cross_val_score(
        model,
        X, y,
        cv=kf,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    )

    cv_results[name] = {
        "mean_mae": scores.mean(),
        "std": scores.std()
    }

pd.DataFrame(cv_results).T.sort_values("mean_mae")

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

        mean_mae       std
cat     0.171089  0.000516
xgb     0.171673  0.000443
lgbm    0.171829  0.000348
rf      0.175569  0.000466
linear  0.242027  0.000454

In [51]:
# CatBoost
cat = CatBoostRegressor(
    iterations=3000,
    learning_rate=0.02,
    depth=6,
    l2_leaf_reg=5,
    random_state=42,
    verbose=0
)

cat.fit(
    X_train, y_train,
    eval_set=(X_valid, y_valid),
    early_stopping_rounds=200
)



# LightGBM
lgbm = LGBMRegressor(
    n_estimators=3000,
    learning_rate=0.02,
    num_leaves=31,
    random_state=42
)

lgbm.fit(
    X_train, y_train,
    eval_set=[(X_valid, y_valid)],
    callbacks=[]
)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.170638 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 417
[LightGBM] [Info] Number of data points in the train set: 504000, number of used features: 13
[LightGBM] [Info] Start training from score 0.448448

LGBMRegressor(learning_rate=0.02, n_estimators=3000, random_state=42)

In [52]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=3000,
    learning_rate=0.02,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    early_stopping_rounds=200   # ⬅️ pindah ke sini
)

xgb.fit(
    X_train, y_train,
    eval_set=[(X_valid, y_valid)],
    verbose=False
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=200,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.02, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=3000,
             n_jobs=None, num_parallel_tree=None, ...)

In [53]:
preds_cat = cat.predict(X_valid)
preds_xgb = xgb.predict(X_valid)
preds_lgbm = lgbm.predict(X_valid)

In [54]:
preds = (
    0.4 * preds_cat +
    0.3 * preds_xgb +
    0.3 * preds_lgbm
)

In [55]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_valid, preds)
mae

0.1702344633923984

In [57]:
X_full = pd.concat([X_train, X_valid])
y_full = pd.concat([y_train, y_valid])

cat.fit(X_full, y_full)
id="fix1"
xgb_final = XGBRegressor(
    n_estimators=xgb.best_iteration,  # ambil dari model sebelumnya
    learning_rate=0.02,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_final.fit(X_full, y_full)
lgbm.fit(X_full, y_full)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.142121 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 415
[LightGBM] [Info] Number of data points in the train set: 630000, number of used features: 13
[LightGBM] [Info] Start training from score 0.448340

LGBMRegressor(learning_rate=0.02, n_estimators=3000, random_state=42)

In [61]:
X_full.head()

,Age,Sex,Chest_pain_type,BP,Cholesterol,FBS_over_120,EKG_results,Max_HR,Exercise_angina,ST_depression,Slope_of_ST,Number_of_vessels_fluro,Thallium
id,,,,,,,,,,,,,
625149,54,1,4,110,274,0,0,125,1,0.4,1,0,7
276435,59,0,3,145,197,0,2,179,0,0.0,3,0,3
43949,64,0,4,160,204,0,0,125,0,0.0,2,0,7
280523,51,0,3,125,248,0,0,188,0,0.0,1,0,3
619977,64,0,4,130,204,0,2,138,0,0.0,1,0,3

In [70]:
dfTest = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e2/test.csv')

In [60]:
dfTest.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7

In [62]:
dfTest = dfTest.set_index('id')

In [63]:
dfTest.info()

<class 'pandas.core.frame.DataFrame'>
Index: 270000 entries, 630000 to 899999
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Age                      270000 non-null  int64
 1   Sex                      270000 non-null  int64
 2   Chest pain type          270000 non-null  int64
 3   BP                       270000 non-null  int64
 4   Cholesterol              270000 non-null  int64
 5   FBS over 120             270000 non-null  int64
 6   EKG results              270000 non-null  int64
 7   Max HR                   270000 non-null  int64
 8   Exercise angina          270000 non-null  int64
 9   ST depression            270000 non-null  float64
 10  Slope of ST              270000 non-null  int64
 11  Number of vessels fluro  270000 non-null  int64
 12  Thallium                 270000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 28.8 MB

In [64]:
dfTest.columns = dfTest.columns.str.replace(' ', '_')

In [66]:
w1, w2, w3 = 0.4, 0.3, 0.3

In [67]:
id="r9i1hz"
preds_test = (
    w1 * cat.predict(dfTest) +
    w2 * xgb.predict(dfTest) +
    w3 * lgbm.predict(dfTest)
)

In [71]:
df_submit = pd.DataFrame({
    "id": dfTest["id"],      # kolom ID dari test.csv
    "target": preds_test      # ganti sesuai nama target
})

In [72]:
df_submit.head()

       id    target
0  630000  0.913216
1  630001  0.032316
2  630002  0.998331
3  630003  0.003574
4  630004  0.241365

In [73]:
df_submit.to_csv('submission.csv', index=False)

In [37]:
dfSubmit = dfSubmit.set_index('id')

In [38]:
dfSubmit.to_csv('submission.csv')