<a href="https://colab.research.google.com/github/Leonanda1013/DataLoverz/blob/main/Competition/Playground/s6e5/1_XGBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
df_test = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e5/test.csv')
df_train = pd.read_csv('/content/drive/MyDrive/DATASET/playground-series-s6e5/train.csv')

In [35]:
df_train.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [36]:
df_test.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,439140,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,439141,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,439142,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,439143,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,439144,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

tanpa cleaning

In [37]:
import xgboost as xgb

In [38]:
X = df_train.drop(['id','PitNextLap'], axis=1)
y = df_train['PitNextLap']

In [39]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=10)

In [40]:
model = xgb.XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=10
)

In [41]:
model.fit(X_train, y_train)
#akan terjadi eror

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:Driver: object, Compound: object, Race: object

Lakukan Clening

In [42]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  object
 2   Compound                439140 non-null  object
 3   Race                    439140 non-null  object
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 53.6+ MB

In [43]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188165 entries, 0 to 188164
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      188165 non-null  int64
 1   Driver                  188165 non-null  object
 2   Compound                188165 non-null  object
 3   Race                    188165 non-null  object
 4   Year                    188165 non-null  int64
 5   PitStop                 188165 non-null  int64
 6   LapNumber               188165 non-null  int64
 7   Stint                   188165 non-null  int64
 8   TyreLife                188165 non-null  float64
 9   Position                188165 non-null  int64
 10  LapTime (s)             188165 non-null  float64
 11  LapTime_Delta           188165 non-null  float64
 12  Cumulative_Degradation  188165 non-null  float64
 13  RaceProgress            188165 non-null  float64
 14  Position_Change         188165 non-null  float64
dtypes: float64(6), int64(6), object(3)
memory usage: 21.5+ MB

In [44]:
df_train['Compound'].value_counts()

Compound
MEDIUM          211141
HARD            170518
SOFT             38744
INTERMEDIATE     17382
WET               1355
Name: count, dtype: int64

In [45]:
df_test['Compound'].value_counts()

Compound
MEDIUM          90897
HARD            72677
SOFT            16615
INTERMEDIATE     7408
WET               568
Name: count, dtype: int64

In [46]:
mapping={
    'WET':0,
    'MEDIUM':2,
    'SOFT':1,
    'INTERMEDIATE':3,
    'HARD':4
}

In [47]:
df_train['Compound'] = df_train['Compound'].map(mapping)
df_test['Compound'] = df_test['Compound'].map(mapping)

In [48]:
df_train.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,4,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,4,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,4,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,2,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,4,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [52]:
df_train['Driver'].value_counts()

Driver
MAS     1682
RAI     1669
BAR     1656
BUT     1655
FIS     1651
        ...
D723       1
D677       1
D731       1
D716       1
D714       1
Name: count, Length: 887, dtype: int64

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
df_train['Driver'] = LabelEncoder().fit_transform(df_train['Driver'])
df_test['Driver'] = LabelEncoder().fit_transform(df_test['Driver'])

In [55]:
df_train['Race'].value_counts()

Race
Dutch Grand Prix             24462
Mexico City Grand Prix       23672
Pre-Season Testing           22492
Hungarian Grand Prix         22481
Monaco Grand Prix            21539
Canadian Grand Prix          21416
Austrian Grand Prix          21223
Spanish Grand Prix           20483
Italian Grand Prix           19854
Bahrain Grand Prix           19535
Singapore Grand Prix         18960
Miami Grand Prix             18860
Australian Grand Prix        18406
Saudi Arabian Grand Prix     18111
United States Grand Prix     18045
Abu Dhabi Grand Prix         16427
Emilia Romagna Grand Prix    15483
British Grand Prix           15383
Qatar Grand Prix             13817
Japanese Grand Prix          12891
Las Vegas Grand Prix         12479
Azerbaijan Grand Prix        12126
São Paulo Grand Prix         11497
Belgian Grand Prix            9002
Chinese Grand Prix            7311
French Grand Prix             3185
Name: count, dtype: int64

In [56]:
df_train['Race'] = LabelEncoder().fit_transform(df_train['Race'])
df_test['Race'] = LabelEncoder().fit_transform(df_test['Race'])

In [49]:
# df_train = pd.get_dummies(df_train, columns=['Driver','Race'],drop_first=True,dtype=int)
# df_test = pd.get_dummies(df_test, columns=['Driver','Race'],drop_first=True,dtype=int)

In [57]:
df_train.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,134,4,7,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,111,4,9,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,886,4,2,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,864,2,19,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,44,4,3,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [58]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  int64
 2   Compound                439140 non-null  int64
 3   Race                    439140 non-null  int64
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(9)
memory usage: 53.6 MB

In [59]:
df_train.set_index('id',inplace=True)
df_test.set_index('id',inplace=True)

In [60]:
X = df_train.drop(['PitNextLap'], axis=1)
y = df_train['PitNextLap']

In [61]:
X_train,_X_test,y_train,_y_test = train_test_split(
    X,y,test_size=0.2,random_state=10)

In [63]:
model = xgb.XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=10
)

In [65]:
model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [67]:
y_pred = model.predict(_X_test)

In [68]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [69]:
print(accuracy_score(_y_test,y_pred))

0.8948968438311244

In [70]:
print(confusion_matrix(_y_test,y_pred))

[[66079  4344]
 [ 4887 12518]]

In [71]:
y_submit = model.predict(df_test)

In [72]:
submission = pd.DataFrame({
    'id':df_test.index,
    'PitNextLap':y_submit
})

In [75]:
import numpy as np

In [78]:
submission.to_csv('submission.csv',index=False)

Coba Optuna Tuning

In [79]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 7.3 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [80]:
import optuna

In [81]:
from sklearn.model_selection import cross_val_score

In [82]:
def objective(trial):
  param = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 500),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "random_state": 42
  }

  model = xgb.XGBClassifier(**param)
  score = cross_val_score(model,X_train,y_train,cv=5,scoring='accuracy')
  accuracy = score.mean()
  return accuracy

In [83]:
study = optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=50)

[I 2026-05-05 12:44:48,057] A new study created in memory with name: no-name-104a06a4-4aad-49c0-aa93-7014e749f21c
[I 2026-05-05 12:45:49,670] Trial 0 finished with value: 0.8966787305930805 and parameters: {'n_estimators': 329, 'max_depth': 6, 'learning_rate': 0.11309039567172086, 'subsample': 0.8259556997413092, 'colsample_bytree': 0.6113415720576331}. Best is trial 0 with value: 0.8966787305930805.
[I 2026-05-05 12:47:57,936] Trial 1 finished with value: 0.8966929669670163 and parameters: {'n_estimators': 331, 'max_depth': 10, 'learning_rate': 0.021158655705002673, 'subsample': 0.8702370423098942, 'colsample_bytree': 0.9298859686420008}. Best is trial 1 with value: 0.8966929669670163.
[I 2026-05-05 12:49:29,699] Trial 2 finished with value: 0.8972195625844573 and parameters: {'n_estimators': 479, 'max_depth': 7, 'learning_rate': 0.11317625637665447, 'subsample': 0.7796585732150322, 'colsample_bytree': 0.8808138622940607}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:49:58,479] Trial 3 finished with value: 0.896012657224255 and parameters: {'n_estimators': 115, 'max_depth': 8, 'learning_rate': 0.2099415051771359, 'subsample': 0.747226907417984, 'colsample_bytree': 0.7958740273649979}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:50:53,739] Trial 4 finished with value: 0.8870861223362848 and parameters: {'n_estimators': 483, 'max_depth': 3, 'learning_rate': 0.06181289320778696, 'subsample': 0.8407572241486119, 'colsample_bytree': 0.644424253808432}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:51:55,082] Trial 5 finished with value: 0.8921756148371062 and parameters: {'n_estimators': 205, 'max_depth': 10, 'learning_rate': 0.2799029517069436, 'subsample': 0.8321928589216937, 'colsample_bytree': 0.841795492615167}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:52:34,325] Trial 6 finished with value: 0.894751667927598 and parameters: {'n_estimators': 253, 'max_depth': 5, 'learning_rate': 0.1408512457367376, 'subsample': 0.8266089024582052, 'colsample_bytree': 0.8851298860313739}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:54:18,317] Trial 7 finished with value: 0.8918397292331225 and parameters: {'n_estimators': 486, 'max_depth': 8, 'learning_rate': 0.2759123631206107, 'subsample': 0.7618678937650749, 'colsample_bytree': 0.6023759780067239}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:56:00,753] Trial 8 finished with value: 0.8910341762898767 and parameters: {'n_estimators': 439, 'max_depth': 8, 'learning_rate': 0.25127120991363383, 'subsample': 0.6816157349168817, 'colsample_bytree': 0.9805967010569784}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:57:23,169] Trial 9 finished with value: 0.8926936717982177 and parameters: {'n_estimators': 306, 'max_depth': 8, 'learning_rate': 0.015590752784569638, 'subsample': 0.8576740781784815, 'colsample_bytree': 0.7163927912576128}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 12:58:15,191] Trial 10 finished with value: 0.8949082248551898 and parameters: {'n_estimators': 426, 'max_depth': 4, 'learning_rate': 0.19298307627230943, 'subsample': 0.9947551074735639, 'colsample_bytree': 0.76924351637556}. Best is trial 2 with value: 0.8972195625844573.
[I 2026-05-05 13:00:08,484] Trial 11 finished with value: 0.8973988895998609 and parameters: {'n_estimators': 386, 'max_depth': 10, 'learning_rate': 0.07705215646217267, 'subsample': 0.9489970685363661, 'colsample_bytree': 0.9451620907276108}. Best is trial 11 with value: 0.8973988895998609.
[I 2026-05-05 13:01:12,795] Trial 12 finished with value: 0.8965307167781293 and parameters: {'n_estimators': 398, 'max_depth': 6, 'learning_rate': 0.09135383852459197, 'subsample': 0.9724665153438278, 'colsample_bytree': 0.9999759127197867}. Best is trial 11 with value: 0.8973988895998609.
[I 2026-05-05 13:02:47,531] Trial 13 finished with value: 0.8981190476748673 and parameters: {'n_estimators': 388, 'max_depth': 9, 'learning_rate': 0.08080897929791507, 'subsample': 0.9276526517166677, 'colsample_bytree': 0.9109133857652318}. Best is trial 13 with value: 0.8981190476748673.
[I 2026-05-05 13:04:37,814] Trial 14 finished with value: 0.8981361254331576 and parameters: {'n_estimators': 364, 'max_depth': 10, 'learning_rate': 0.07197673264400718, 'subsample': 0.9282787558225104, 'colsample_bytree': 0.9125248995690627}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:06:11,704] Trial 15 finished with value: 0.8979254859465164 and parameters: {'n_estimators': 366, 'max_depth': 9, 'learning_rate': 0.04924683975346585, 'subsample': 0.9139671764642557, 'colsample_bytree': 0.8507382934913623}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:07:20,730] Trial 16 finished with value: 0.8962659913294377 and parameters: {'n_estimators': 270, 'max_depth': 9, 'learning_rate': 0.16086159203753908, 'subsample': 0.909425279674743, 'colsample_bytree': 0.9194995720880517}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:08:22,190] Trial 17 finished with value: 0.8972024834892739 and parameters: {'n_estimators': 214, 'max_depth': 9, 'learning_rate': 0.047399143343856295, 'subsample': 0.6277889770658942, 'colsample_bytree': 0.7366191420082022}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:09:24,928] Trial 18 finished with value: 0.897205326980248 and parameters: {'n_estimators': 354, 'max_depth': 7, 'learning_rate': 0.13703363248574735, 'subsample': 0.9244921595121797, 'colsample_bytree': 0.8372050433330211}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:11:32,912] Trial 19 finished with value: 0.8968495219500362 and parameters: {'n_estimators': 432, 'max_depth': 10, 'learning_rate': 0.09861955538628862, 'subsample': 0.882543551069996, 'colsample_bytree': 0.8991635893573288}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:12:06,874] Trial 20 finished with value: 0.8964424776897012 and parameters: {'n_estimators': 133, 'max_depth': 9, 'learning_rate': 0.17394980150878517, 'subsample': 0.9986918028162297, 'colsample_bytree': 0.9580373768911103}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:13:47,757] Trial 21 finished with value: 0.8979226391740772 and parameters: {'n_estimators': 378, 'max_depth': 9, 'learning_rate': 0.04206449980431698, 'subsample': 0.9157242946725727, 'colsample_bytree': 0.8604632183527402}. Best is trial 14 with value: 0.8981361254331576.
[I 2026-05-05 13:15:16,578] Trial 22 finished with value: 0.8982784473642186 and parameters: {'n_estimators': 359, 'max_depth': 9, 'learning_rate': 0.06662482751421175, 'subsample': 0.947674957988601, 'colsample_bytree': 0.8213264874684367}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:16:39,375] Trial 23 finished with value: 0.8979624909093232 and parameters: {'n_estimators': 277, 'max_depth': 10, 'learning_rate': 0.08482110389070961, 'subsample': 0.9515862396844051, 'colsample_bytree': 0.8036482077377723}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:17:39,659] Trial 24 finished with value: 0.897612375575358 and parameters: {'n_estimators': 338, 'max_depth': 7, 'learning_rate': 0.12292886721167104, 'subsample': 0.956622214902201, 'colsample_bytree': 0.8199993533536724}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:19:29,194] Trial 25 finished with value: 0.898027958248951 and parameters: {'n_estimators': 407, 'max_depth': 9, 'learning_rate': 0.03304912442758421, 'subsample': 0.8876755393226602, 'colsample_bytree': 0.9116046792466109}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:20:39,347] Trial 26 finished with value: 0.898101967890981 and parameters: {'n_estimators': 303, 'max_depth': 8, 'learning_rate': 0.06973842257372626, 'subsample': 0.7129412927080628, 'colsample_bytree': 0.7497010299117544}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:22:51,806] Trial 27 finished with value: 0.8979511054805542 and parameters: {'n_estimators': 444, 'max_depth': 10, 'learning_rate': 0.06606267264509735, 'subsample': 0.9396465517094184, 'colsample_bytree': 0.9580807565623539}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:24:14,870] Trial 28 finished with value: 0.8977945489985935 and parameters: {'n_estimators': 357, 'max_depth': 9, 'learning_rate': 0.10533240720801428, 'subsample': 0.9757170080393119, 'colsample_bytree': 0.7091782848523086}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:25:17,655] Trial 29 finished with value: 0.8848487961936191 and parameters: {'n_estimators': 319, 'max_depth': 6, 'learning_rate': 0.010682693874037752, 'subsample': 0.7912111742228073, 'colsample_bytree': 0.8810462495693946}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:26:00,612] Trial 30 finished with value: 0.8968950620041237 and parameters: {'n_estimators': 220, 'max_depth': 7, 'learning_rate': 0.1307859922022152, 'subsample': 0.8928610078588171, 'colsample_bytree': 0.7711004142601616}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:27:04,595] Trial 31 finished with value: 0.8976636102681462 and parameters: {'n_estimators': 285, 'max_depth': 8, 'learning_rate': 0.06977109314281774, 'subsample': 0.7092152194089922, 'colsample_bytree': 0.658712872649502}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:28:16,850] Trial 32 finished with value: 0.8976949233470627 and parameters: {'n_estimators': 302, 'max_depth': 8, 'learning_rate': 0.05767102557362598, 'subsample': 0.6017463563257477, 'colsample_bytree': 0.7458755264181911}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:30:10,207] Trial 33 finished with value: 0.8977319271755357 and parameters: {'n_estimators': 340, 'max_depth': 10, 'learning_rate': 0.030659013794948384, 'subsample': 0.7085264678219381, 'colsample_bytree': 0.6954530278047495}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:31:58,041] Trial 34 finished with value: 0.8957849390070376 and parameters: {'n_estimators': 406, 'max_depth': 9, 'learning_rate': 0.11087922135535695, 'subsample': 0.6684845846887405, 'colsample_bytree': 0.9330490428459541}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:33:36,653] Trial 35 finished with value: 0.897666455906252 and parameters: {'n_estimators': 458, 'max_depth': 8, 'learning_rate': 0.08815509859013439, 'subsample': 0.8065419526224716, 'colsample_bytree': 0.7937806837196284}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:34:56,975] Trial 36 finished with value: 0.8981788226039498 and parameters: {'n_estimators': 319, 'max_depth': 9, 'learning_rate': 0.07633482548452121, 'subsample': 0.7358049495264011, 'colsample_bytree': 0.6769441966650779}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:36:47,055] Trial 37 finished with value: 0.8978258593632116 and parameters: {'n_estimators': 329, 'max_depth': 10, 'learning_rate': 0.02893811343607227, 'subsample': 0.8469263982868398, 'colsample_bytree': 0.67242434445559}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:37:23,604] Trial 38 finished with value: 0.8940941355242817 and parameters: {'n_estimators': 240, 'max_depth': 5, 'learning_rate': 0.11848243288297719, 'subsample': 0.7389662446746403, 'colsample_bytree': 0.8635937577138041}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:39:15,599] Trial 39 finished with value: 0.8972053275879268 and parameters: {'n_estimators': 374, 'max_depth': 10, 'learning_rate': 0.0994789151296923, 'subsample': 0.8651739463725819, 'colsample_bytree': 0.8259402194080492}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:40:02,496] Trial 40 finished with value: 0.8966588057382554 and parameters: {'n_estimators': 165, 'max_depth': 9, 'learning_rate': 0.057257741896097794, 'subsample': 0.81233256094124, 'colsample_bytree': 0.6237914371661273}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:41:14,607] Trial 41 finished with value: 0.8980279587756058 and parameters: {'n_estimators': 315, 'max_depth': 8, 'learning_rate': 0.0738310658742706, 'subsample': 0.773371526720102, 'colsample_bytree': 0.6756901850743259}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:42:44,454] Trial 42 finished with value: 0.8980763489646222 and parameters: {'n_estimators': 349, 'max_depth': 9, 'learning_rate': 0.07909837332341853, 'subsample': 0.7444958854417406, 'colsample_bytree': 0.6343786030614746}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:43:52,745] Trial 43 finished with value: 0.8939176539444244 and parameters: {'n_estimators': 292, 'max_depth': 8, 'learning_rate': 0.23020620980134965, 'subsample': 0.7141149521659129, 'colsample_bytree': 0.7689785269960064}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:45:10,711] Trial 44 finished with value: 0.8944186316888164 and parameters: {'n_estimators': 256, 'max_depth': 10, 'learning_rate': 0.15381799332997542, 'subsample': 0.6512840136016083, 'colsample_bytree': 0.7375282679169561}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:47:00,519] Trial 45 finished with value: 0.8981076597748713 and parameters: {'n_estimators': 389, 'max_depth': 9, 'learning_rate': 0.041410586858981906, 'subsample': 0.7239885522245595, 'colsample_bytree': 0.8997284759736935}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:48:42,875] Trial 46 finished with value: 0.8981418180057504 and parameters: {'n_estimators': 393, 'max_depth': 9, 'learning_rate': 0.04543042312627589, 'subsample': 0.9763786640027239, 'colsample_bytree': 0.9098648805738049}. Best is trial 22 with value: 0.8982784473642186.
[I 2026-05-05 13:50:47,708] Trial 47 finished with value: 0.8983780758110717 and parameters: {'n_estimators': 412, 'max_depth': 10, 'learning_rate': 0.055582681409380254, 'subsample': 0.967063161179112, 'colsample_bytree': 0.9804913252113854}. Best is trial 47 with value: 0.8983780758110717.
[I 2026-05-05 13:51:34,081] Trial 48 finished with value: 0.8805022318151039 and parameters: {'n_estimators': 419, 'max_depth': 3, 'learning_rate': 0.025610532511000213, 'subsample': 0.9770713431251509, 'colsample_bytree': 0.9946547867523039}. Best is trial 47 with value: 0.8983780758110717.
[I 2026-05-05 13:54:00,488] Trial 49 finished with value: 0.8983325320703995 and parameters: {'n_estimators': 466, 'max_depth': 10, 'learning_rate': 0.04555983203477591, 'subsample': 0.9628055606811107, 'colsample_bytree': 0.963142928229674}. Best is trial 47 with value: 0.8983780758110717.

In [85]:
print(study.best_params)

{'n_estimators': 412, 'max_depth': 10, 'learning_rate': 0.055582681409380254, 'subsample': 0.967063161179112, 'colsample_bytree': 0.9804913252113854}

In [86]:
print("Best score:", study.best_value)

Best score: 0.8983780758110717

In [88]:
best_model = xgb.XGBClassifier(**study.best_params)
best_model.fit(X_train, y_train)

y_pred = best_model.predict(_X_test)

In [89]:
y_submit = best_model.predict(df_test)

In [90]:
submission = pd.DataFrame({
    'id':df_test.index,
    'PitNextLap':y_submit
})

In [91]:
submission.to_csv('submission_2.csv',index=False)